pipeline:
  identifier: Build_kleinjoshuaa_boxesdemo_nodejs_1719838707593
  name: Build boxesdemo-nodejs
  orgIdentifier: default
  projectIdentifier: Split_CICD_pipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1719363520503
        repoName: kleinjoshuaa/boxesdemo-nodejs
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
